# -*- coding: utf-8 -*-
"""Progres4.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZO5vTPlVP6t5-onnEet2fIkUt4_hoO6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from pandas.core.common import random_state
from sklearn.linear_model import LinearRegression

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/Processed/Processed4
df = pd.read_csv("pengaruhReputasi.csv")
df.head()

df.describe()

df.isnull().sum()

plt.title('pd_score Distribution Plot')
sns.distplot(df['pd_score'])
plt.show()

plt.scatter(df['Reputation'], df['pd_score'], color='blue')
plt.title('Reputation vs pd_score')
plt.xlabel('Reputation')
plt.ylabel('pd_score')
plt.box(False)
plt.show()

X = df.iloc[:, : 1]
y = df.iloc[:, 1 :]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred_train = regressor.predict(X_train)
y_pred_test = regressor.predict(X_test)

plt.scatter(X_train, y_train, color='lightcoral')
plt.plot(X_train, y_pred_train, color='firebrick')
plt.title('Reputation vs pd_score (Training Set)')
plt.xlabel('Reputation')
plt.ylabel('pd_score')
plt.legend(['X_train/Pred(y_test)', 'X_train/y_train'], title = 'pd_score/Reputation', facecolor = 'white')
plt.box(False)
plt.show()

plt.scatter(X_test, y_test, color='lightcoral')
plt.plot(X_train, y_pred_train, color='firebrick')
plt.title('Reputation vs pd_score (Test Set)')
plt.xlabel('Reputation')
plt.ylabel('pd_score')
plt.legend(['X_train/Pred(y_test)', 'X_train/y_train'], title = 'pd_score/Reputation', facecolor = 'white')
plt.box(False)
plt.show()

print(f'Coeficients: {regressor.coef_}')
print(f'Intercept: {regressor.intercept_}')